DROP TABLE IF EXISTS waveMaps;

CREATE TABLE waveMaps(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    map TEXT NOT NULL,
    description TEXT NOT NULL,
    spu FLOAT NOT NULL
)